### ISSUE TITLE
Integration with rails

### ISSUE THREAD

**Issue by e-jjj** [Thinkei/opencensus-ruby-exporter-jaeger#15]
What is the best way to integrate opencensus-ruby-exporter-jeager with rails?
@luong-komorebi

**Comment by luong-komorebi** [comment]
@e-jjj Could you take a look at examples folder? I leave an example there on how we can integrate this with Rails. Dont hesitate leaving more comments here if you still have problems using this

**Comment by e-jjj** [comment]
@luong-komorebi I did take a look at the examples folder, but it looks that it uses the Rack Middleware integration only?
Can you please point me to the rails integration?

I'm testing out the Rack Middleware and facing this error in a rails app,

`Rack app error handling request { GET /ping }
#<RuntimeError: No currently active span context>`

**Comment by luong-komorebi** [comment]
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/15828926/73515758-fea79e80-4428-11ea-8bef-38d502645055.png">
^ This is the result when I run example. 
Also, for 
>  I did take a look at the examples folder, but it looks that it uses the Rack Middleware integration only?
We integrate at Rack level so that Rails and other framework based on Rack (Sinatra) can make use of it. Anyway, I believe your concern should go to https://github.com/census-instrumentation/opencensus-ruby (please read their readme) because here this lib only takes care of exporting the traces, not recording them

**Comment by luong-komorebi** [comment]
I ll close this issue, but feel free to comment here if there are any concerns that we should address
